name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://${{vars.MONGO_USERNAME}}:${{secrets.MONGO_PASSWORD}}@cluster0.dqmuih9.mongodb.net/test?retryWrites=true&w=majority'

jobs:
    unit-testing:
        name: Unit Testing
        # strategy:
        #   matrix:
        #     nodejs_version: [18]
        #     os: [ubuntu-latest]
            
              
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version  ${{matrix.nodejs_version}}
          uses: actions/setup-node@v3
          with:
            node-version: 18
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v7
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    codecoverage:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: setup NodeJS Version - 18
        uses: action/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependency
        run: npm install
      - name: Code Coverage
        run: npm run coverage
      - name: Archive coverage Result 
        uses: actions/upload-artifact@v7
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5